<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2019/06/22 01:22:50

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=dbname',
  'username' => 'root',
  'password' => 'mYsEcret',
  'name' => 'doctrine',
)),);
