<?php
// auto-generated by sfFilterConfigHandler
// date: 2019/06/22 01:22:50


list($class, $parameters) = (array) sfConfig::get('sf_rendering_filter', array('sfRenderingFilter', array (
)));
$filter = new $class(sfContext::getInstance(), $parameters);
$this->register($filter);

// does this action require security?
if ($actionInstance->isSecure())
{
  
list($class, $parameters) = (array) sfConfig::get('sf_security_filter', array('sfBasicSecurityFilter', array (
)));
$filter = new $class(sfContext::getInstance(), $parameters);
$this->register($filter);
}

list($class, $parameters) = (array) sfConfig::get('sf_TestFilter_filter', array('TestFilter', array (
  'applicationId' => 'eyJhcHAiOiI2NjA6NjUiLCJ2ZXIiOiIyLjAiLCJvcmciOiIyMDc6MTE2IiwiaWF0IjoxNTYwMzg0MDAwfQ.vvlpq-Fg2xeBT-1pJNhQO4-Fg0_7zcdoV1D6a62ZI-8',
  'debug' => true,
)));
$filter = new $class(sfContext::getInstance(), $parameters);
$this->register($filter);

list($class, $parameters) = (array) sfConfig::get('sf_execution_filter', array('sfExecutionFilter', array (
)));
$filter = new $class(sfContext::getInstance(), $parameters);
$this->register($filter);

